import { StyleSheet } from "react-native";

export const makeStyles = (theme) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: theme.overlay || "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    scrollContainer: {
      flexGrow: 1,
      justifyContent: "flex-end",
    },
    modalContainer: {
      backgroundColor: theme.modalBg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingTop: 24,
      paddingHorizontal: 24,
      paddingBottom: 40,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 12,
      width: "100%",
    },
    closeButton: {
      alignSelf: "flex-end",
      padding: 8,
      marginRight: -8,
      marginBottom: 8,
    },
    iconContainer: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: theme.primary + "15",
      justifyContent: "center",
      alignItems: "center",
      alignSelf: "center",
      marginBottom: 20,
    },
    title: {
      fontSize: 22,
      fontWeight: "800",
      color: theme.text,
      textAlign: "center",
      marginBottom: 12,
    },
    subtitle: {
      fontSize: 15,
      color: theme.subtext,
      textAlign: "center",
      lineHeight: 22,
      marginBottom: 24,
      paddingHorizontal: 10,
    },
    contactInfo: {
      backgroundColor: theme.primary + "10",
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderRadius: 12,
      marginBottom: 24,
      alignItems: "center",
    },
    contactLabel: {
      fontSize: 12,
      color: theme.subtext,
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 6,
    },
    contactValue: {
      fontSize: 15,
      color: theme.text,
      fontWeight: "700",
    },
    content: {
      marginTop: 8,
    },
    stepDescription: {
      fontSize: 14,
      color: theme.subtext,
      lineHeight: 20,
      marginBottom: 20,
      textAlign: "center",
    },
    codeInputContainer: {
      marginBottom: 16,
    },
    codeInput: {
      backgroundColor: theme.card,
      fontSize: 16,
      letterSpacing: 4,
      fontWeight: "600",
      textAlign: "center",
    },
    timerContainer: {
      alignItems: "center",
      marginBottom: 20,
      minHeight: 24,
    },
    timerText: {
      fontSize: 13,
      color: theme.subtext,
      fontWeight: "500",
    },
    resendLink: {
      fontSize: 13,
      color: theme.primary,
      fontWeight: "600",
      textDecorationLine: "underline",
    },
    primaryButton: {
      backgroundColor: theme.primary,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    secondaryButton: {
      borderWidth: 1.5,
      borderColor: theme.borderLight,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: "center",
    },
    primaryButtonText: {
      color: "#fff",
      fontSize: 15,
      fontWeight: "700",
      letterSpacing: 0.3,
    },
    secondaryButtonText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: "600",
    },
    buttonDisabled: {
      opacity: 0.6,
    },
  });
